# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from gazebo_sensor_collection/EncoderData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import genpy

class EncoderData(genpy.Message):
  _md5sum = "e2549cfa0ef2aec74010dcef181ee872"
  _type = "gazebo_sensor_collection/EncoderData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time stamp
int32 id
float64 position
float64 speed
float64 qpps
"""
  __slots__ = ['stamp','id','position','speed','qpps']
  _slot_types = ['time','int32','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,id,position,speed,qpps

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(EncoderData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.id is None:
        self.id = 0
      if self.position is None:
        self.position = 0.
      if self.speed is None:
        self.speed = 0.
      if self.qpps is None:
        self.qpps = 0.
    else:
      self.stamp = genpy.Time()
      self.id = 0
      self.position = 0.
      self.speed = 0.
      self.qpps = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2Ii3d().pack(_x.stamp.secs, _x.stamp.nsecs, _x.id, _x.position, _x.speed, _x.qpps))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 36
      (_x.stamp.secs, _x.stamp.nsecs, _x.id, _x.position, _x.speed, _x.qpps,) = _get_struct_2Ii3d().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2Ii3d().pack(_x.stamp.secs, _x.stamp.nsecs, _x.id, _x.position, _x.speed, _x.qpps))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      end = 0
      _x = self
      start = end
      end += 36
      (_x.stamp.secs, _x.stamp.nsecs, _x.id, _x.position, _x.speed, _x.qpps,) = _get_struct_2Ii3d().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2Ii3d = None
def _get_struct_2Ii3d():
    global _struct_2Ii3d
    if _struct_2Ii3d is None:
        _struct_2Ii3d = struct.Struct("<2Ii3d")
    return _struct_2Ii3d
