# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from gazebo_sensor_collection/GpsData.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import gazebo_sensor_collection.msg
import genpy

class GpsData(genpy.Message):
  _md5sum = "c8616250764453b7cd4fbceca47db6ba"
  _type = "gazebo_sensor_collection/GpsData"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """time stamp
float64 latitude
float64 longitude
float64 altitude
float64 reference_latitude
float64 reference_longitude
float64 reference_altitude
float64 reference_heading
DataXYZ velocity
DataXYZ covariance
uint8 covariance_type
uint16 service
int8 status

================================================================================
MSG: gazebo_sensor_collection/DataXYZ
float64 x
float64 y
float64 z
"""
  __slots__ = ['stamp','latitude','longitude','altitude','reference_latitude','reference_longitude','reference_altitude','reference_heading','velocity','covariance','covariance_type','service','status']
  _slot_types = ['time','float64','float64','float64','float64','float64','float64','float64','gazebo_sensor_collection/DataXYZ','gazebo_sensor_collection/DataXYZ','uint8','uint16','int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,latitude,longitude,altitude,reference_latitude,reference_longitude,reference_altitude,reference_heading,velocity,covariance,covariance_type,service,status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GpsData, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.latitude is None:
        self.latitude = 0.
      if self.longitude is None:
        self.longitude = 0.
      if self.altitude is None:
        self.altitude = 0.
      if self.reference_latitude is None:
        self.reference_latitude = 0.
      if self.reference_longitude is None:
        self.reference_longitude = 0.
      if self.reference_altitude is None:
        self.reference_altitude = 0.
      if self.reference_heading is None:
        self.reference_heading = 0.
      if self.velocity is None:
        self.velocity = gazebo_sensor_collection.msg.DataXYZ()
      if self.covariance is None:
        self.covariance = gazebo_sensor_collection.msg.DataXYZ()
      if self.covariance_type is None:
        self.covariance_type = 0
      if self.service is None:
        self.service = 0
      if self.status is None:
        self.status = 0
    else:
      self.stamp = genpy.Time()
      self.latitude = 0.
      self.longitude = 0.
      self.altitude = 0.
      self.reference_latitude = 0.
      self.reference_longitude = 0.
      self.reference_altitude = 0.
      self.reference_heading = 0.
      self.velocity = gazebo_sensor_collection.msg.DataXYZ()
      self.covariance = gazebo_sensor_collection.msg.DataXYZ()
      self.covariance_type = 0
      self.service = 0
      self.status = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2I13dBHb().pack(_x.stamp.secs, _x.stamp.nsecs, _x.latitude, _x.longitude, _x.altitude, _x.reference_latitude, _x.reference_longitude, _x.reference_altitude, _x.reference_heading, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.covariance.x, _x.covariance.y, _x.covariance.z, _x.covariance_type, _x.service, _x.status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.velocity is None:
        self.velocity = gazebo_sensor_collection.msg.DataXYZ()
      if self.covariance is None:
        self.covariance = gazebo_sensor_collection.msg.DataXYZ()
      end = 0
      _x = self
      start = end
      end += 116
      (_x.stamp.secs, _x.stamp.nsecs, _x.latitude, _x.longitude, _x.altitude, _x.reference_latitude, _x.reference_longitude, _x.reference_altitude, _x.reference_heading, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.covariance.x, _x.covariance.y, _x.covariance.z, _x.covariance_type, _x.service, _x.status,) = _get_struct_2I13dBHb().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2I13dBHb().pack(_x.stamp.secs, _x.stamp.nsecs, _x.latitude, _x.longitude, _x.altitude, _x.reference_latitude, _x.reference_longitude, _x.reference_altitude, _x.reference_heading, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.covariance.x, _x.covariance.y, _x.covariance.z, _x.covariance_type, _x.service, _x.status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.velocity is None:
        self.velocity = gazebo_sensor_collection.msg.DataXYZ()
      if self.covariance is None:
        self.covariance = gazebo_sensor_collection.msg.DataXYZ()
      end = 0
      _x = self
      start = end
      end += 116
      (_x.stamp.secs, _x.stamp.nsecs, _x.latitude, _x.longitude, _x.altitude, _x.reference_latitude, _x.reference_longitude, _x.reference_altitude, _x.reference_heading, _x.velocity.x, _x.velocity.y, _x.velocity.z, _x.covariance.x, _x.covariance.y, _x.covariance.z, _x.covariance_type, _x.service, _x.status,) = _get_struct_2I13dBHb().unpack(str[start:end])
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I13dBHb = None
def _get_struct_2I13dBHb():
    global _struct_2I13dBHb
    if _struct_2I13dBHb is None:
        _struct_2I13dBHb = struct.Struct("<2I13dBHb")
    return _struct_2I13dBHb
