# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from gazebo_sensor_collection/SensorData3D.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import gazebo_sensor_collection.msg

class SensorData3D(genpy.Message):
  _md5sum = "513fdfd0e6bee20a157cc975187a992e"
  _type = "gazebo_sensor_collection/SensorData3D"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64 x
float64 y
float64 z
DataXYZ covariance
DataXYZ bias
DataXYZ offset

================================================================================
MSG: gazebo_sensor_collection/DataXYZ
float64 x
float64 y
float64 z
"""
  __slots__ = ['x','y','z','covariance','bias','offset']
  _slot_types = ['float64','float64','float64','gazebo_sensor_collection/DataXYZ','gazebo_sensor_collection/DataXYZ','gazebo_sensor_collection/DataXYZ']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       x,y,z,covariance,bias,offset

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SensorData3D, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.x is None:
        self.x = 0.
      if self.y is None:
        self.y = 0.
      if self.z is None:
        self.z = 0.
      if self.covariance is None:
        self.covariance = gazebo_sensor_collection.msg.DataXYZ()
      if self.bias is None:
        self.bias = gazebo_sensor_collection.msg.DataXYZ()
      if self.offset is None:
        self.offset = gazebo_sensor_collection.msg.DataXYZ()
    else:
      self.x = 0.
      self.y = 0.
      self.z = 0.
      self.covariance = gazebo_sensor_collection.msg.DataXYZ()
      self.bias = gazebo_sensor_collection.msg.DataXYZ()
      self.offset = gazebo_sensor_collection.msg.DataXYZ()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_12d().pack(_x.x, _x.y, _x.z, _x.covariance.x, _x.covariance.y, _x.covariance.z, _x.bias.x, _x.bias.y, _x.bias.z, _x.offset.x, _x.offset.y, _x.offset.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.covariance is None:
        self.covariance = gazebo_sensor_collection.msg.DataXYZ()
      if self.bias is None:
        self.bias = gazebo_sensor_collection.msg.DataXYZ()
      if self.offset is None:
        self.offset = gazebo_sensor_collection.msg.DataXYZ()
      end = 0
      _x = self
      start = end
      end += 96
      (_x.x, _x.y, _x.z, _x.covariance.x, _x.covariance.y, _x.covariance.z, _x.bias.x, _x.bias.y, _x.bias.z, _x.offset.x, _x.offset.y, _x.offset.z,) = _get_struct_12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_12d().pack(_x.x, _x.y, _x.z, _x.covariance.x, _x.covariance.y, _x.covariance.z, _x.bias.x, _x.bias.y, _x.bias.z, _x.offset.x, _x.offset.y, _x.offset.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.covariance is None:
        self.covariance = gazebo_sensor_collection.msg.DataXYZ()
      if self.bias is None:
        self.bias = gazebo_sensor_collection.msg.DataXYZ()
      if self.offset is None:
        self.offset = gazebo_sensor_collection.msg.DataXYZ()
      end = 0
      _x = self
      start = end
      end += 96
      (_x.x, _x.y, _x.z, _x.covariance.x, _x.covariance.y, _x.covariance.z, _x.bias.x, _x.bias.y, _x.bias.z, _x.offset.x, _x.offset.y, _x.offset.z,) = _get_struct_12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12d = None
def _get_struct_12d():
    global _struct_12d
    if _struct_12d is None:
        _struct_12d = struct.Struct("<12d")
    return _struct_12d
