// Generated by gencpp from file gazebo_sensor_collection/BatteryData.msg
// DO NOT EDIT!


#ifndef GAZEBO_SENSOR_COLLECTION_MESSAGE_BATTERYDATA_H
#define GAZEBO_SENSOR_COLLECTION_MESSAGE_BATTERYDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gazebo_sensor_collection
{
template <class ContainerAllocator>
struct BatteryData_
{
  typedef BatteryData_<ContainerAllocator> Type;

  BatteryData_()
    : stamp()
    , voltage(0.0)
    , vmax(0.0)
    , vmin(0.0)  {
    }
  BatteryData_(const ContainerAllocator& _alloc)
    : stamp()
    , voltage(0.0)
    , vmax(0.0)
    , vmin(0.0)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef double _voltage_type;
  _voltage_type voltage;

   typedef double _vmax_type;
  _vmax_type vmax;

   typedef double _vmin_type;
  _vmin_type vmin;





  typedef boost::shared_ptr< ::gazebo_sensor_collection::BatteryData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_sensor_collection::BatteryData_<ContainerAllocator> const> ConstPtr;

}; // struct BatteryData_

typedef ::gazebo_sensor_collection::BatteryData_<std::allocator<void> > BatteryData;

typedef boost::shared_ptr< ::gazebo_sensor_collection::BatteryData > BatteryDataPtr;
typedef boost::shared_ptr< ::gazebo_sensor_collection::BatteryData const> BatteryDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_sensor_collection::BatteryData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_sensor_collection::BatteryData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gazebo_sensor_collection::BatteryData_<ContainerAllocator1> & lhs, const ::gazebo_sensor_collection::BatteryData_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.voltage == rhs.voltage &&
    lhs.vmax == rhs.vmax &&
    lhs.vmin == rhs.vmin;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gazebo_sensor_collection::BatteryData_<ContainerAllocator1> & lhs, const ::gazebo_sensor_collection::BatteryData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gazebo_sensor_collection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gazebo_sensor_collection::BatteryData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_sensor_collection::BatteryData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_sensor_collection::BatteryData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_sensor_collection::BatteryData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_sensor_collection::BatteryData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_sensor_collection::BatteryData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_sensor_collection::BatteryData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6a9bbba12ac00a99cf3603ae02c56555";
  }

  static const char* value(const ::gazebo_sensor_collection::BatteryData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6a9bbba12ac00a99ULL;
  static const uint64_t static_value2 = 0xcf3603ae02c56555ULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_sensor_collection::BatteryData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_sensor_collection/BatteryData";
  }

  static const char* value(const ::gazebo_sensor_collection::BatteryData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_sensor_collection::BatteryData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"float64 voltage\n"
"float64 vmax\n"
"float64 vmin\n"
;
  }

  static const char* value(const ::gazebo_sensor_collection::BatteryData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_sensor_collection::BatteryData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.voltage);
      stream.next(m.vmax);
      stream.next(m.vmin);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BatteryData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_sensor_collection::BatteryData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_sensor_collection::BatteryData_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "voltage: ";
    Printer<double>::stream(s, indent + "  ", v.voltage);
    s << indent << "vmax: ";
    Printer<double>::stream(s, indent + "  ", v.vmax);
    s << indent << "vmin: ";
    Printer<double>::stream(s, indent + "  ", v.vmin);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_SENSOR_COLLECTION_MESSAGE_BATTERYDATA_H
