// Generated by gencpp from file gazebo_sensor_collection/EulerData.msg
// DO NOT EDIT!


#ifndef GAZEBO_SENSOR_COLLECTION_MESSAGE_EULERDATA_H
#define GAZEBO_SENSOR_COLLECTION_MESSAGE_EULERDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gazebo_sensor_collection
{
template <class ContainerAllocator>
struct EulerData_
{
  typedef EulerData_<ContainerAllocator> Type;

  EulerData_()
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
    }
  EulerData_(const ContainerAllocator& _alloc)
    : roll(0.0)
    , pitch(0.0)
    , yaw(0.0)  {
  (void)_alloc;
    }



   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _yaw_type;
  _yaw_type yaw;





  typedef boost::shared_ptr< ::gazebo_sensor_collection::EulerData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_sensor_collection::EulerData_<ContainerAllocator> const> ConstPtr;

}; // struct EulerData_

typedef ::gazebo_sensor_collection::EulerData_<std::allocator<void> > EulerData;

typedef boost::shared_ptr< ::gazebo_sensor_collection::EulerData > EulerDataPtr;
typedef boost::shared_ptr< ::gazebo_sensor_collection::EulerData const> EulerDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_sensor_collection::EulerData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_sensor_collection::EulerData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gazebo_sensor_collection::EulerData_<ContainerAllocator1> & lhs, const ::gazebo_sensor_collection::EulerData_<ContainerAllocator2> & rhs)
{
  return lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.yaw == rhs.yaw;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gazebo_sensor_collection::EulerData_<ContainerAllocator1> & lhs, const ::gazebo_sensor_collection::EulerData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gazebo_sensor_collection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gazebo_sensor_collection::EulerData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_sensor_collection::EulerData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_sensor_collection::EulerData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_sensor_collection::EulerData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_sensor_collection::EulerData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_sensor_collection::EulerData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_sensor_collection::EulerData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eeec8b25a660789a89540dedcb2b06d6";
  }

  static const char* value(const ::gazebo_sensor_collection::EulerData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeeec8b25a660789aULL;
  static const uint64_t static_value2 = 0x89540dedcb2b06d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_sensor_collection::EulerData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_sensor_collection/EulerData";
  }

  static const char* value(const ::gazebo_sensor_collection::EulerData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_sensor_collection::EulerData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
;
  }

  static const char* value(const ::gazebo_sensor_collection::EulerData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_sensor_collection::EulerData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EulerData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_sensor_collection::EulerData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_sensor_collection::EulerData_<ContainerAllocator>& v)
  {
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<double>::stream(s, indent + "  ", v.yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_SENSOR_COLLECTION_MESSAGE_EULERDATA_H
