// Generated by gencpp from file gazebo_sensor_collection/ImuData.msg
// DO NOT EDIT!


#ifndef GAZEBO_SENSOR_COLLECTION_MESSAGE_IMUDATA_H
#define GAZEBO_SENSOR_COLLECTION_MESSAGE_IMUDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <gazebo_sensor_collection/SensorData3D.h>
#include <gazebo_sensor_collection/SensorData3D.h>
#include <gazebo_sensor_collection/OrientationSensorData.h>

namespace gazebo_sensor_collection
{
template <class ContainerAllocator>
struct ImuData_
{
  typedef ImuData_<ContainerAllocator> Type;

  ImuData_()
    : stamp()
    , accel()
    , gyro()
    , orientation()  {
    }
  ImuData_(const ContainerAllocator& _alloc)
    : stamp()
    , accel(_alloc)
    , gyro(_alloc)
    , orientation(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef  ::gazebo_sensor_collection::SensorData3D_<ContainerAllocator>  _accel_type;
  _accel_type accel;

   typedef  ::gazebo_sensor_collection::SensorData3D_<ContainerAllocator>  _gyro_type;
  _gyro_type gyro;

   typedef  ::gazebo_sensor_collection::OrientationSensorData_<ContainerAllocator>  _orientation_type;
  _orientation_type orientation;





  typedef boost::shared_ptr< ::gazebo_sensor_collection::ImuData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gazebo_sensor_collection::ImuData_<ContainerAllocator> const> ConstPtr;

}; // struct ImuData_

typedef ::gazebo_sensor_collection::ImuData_<std::allocator<void> > ImuData;

typedef boost::shared_ptr< ::gazebo_sensor_collection::ImuData > ImuDataPtr;
typedef boost::shared_ptr< ::gazebo_sensor_collection::ImuData const> ImuDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gazebo_sensor_collection::ImuData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gazebo_sensor_collection::ImuData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gazebo_sensor_collection::ImuData_<ContainerAllocator1> & lhs, const ::gazebo_sensor_collection::ImuData_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.accel == rhs.accel &&
    lhs.gyro == rhs.gyro &&
    lhs.orientation == rhs.orientation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gazebo_sensor_collection::ImuData_<ContainerAllocator1> & lhs, const ::gazebo_sensor_collection::ImuData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gazebo_sensor_collection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gazebo_sensor_collection::ImuData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gazebo_sensor_collection::ImuData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_sensor_collection::ImuData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gazebo_sensor_collection::ImuData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_sensor_collection::ImuData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gazebo_sensor_collection::ImuData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gazebo_sensor_collection::ImuData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4dd12c4714f677eadc16e5447a415b6a";
  }

  static const char* value(const ::gazebo_sensor_collection::ImuData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4dd12c4714f677eaULL;
  static const uint64_t static_value2 = 0xdc16e5447a415b6aULL;
};

template<class ContainerAllocator>
struct DataType< ::gazebo_sensor_collection::ImuData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gazebo_sensor_collection/ImuData";
  }

  static const char* value(const ::gazebo_sensor_collection::ImuData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gazebo_sensor_collection::ImuData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"SensorData3D accel\n"
"SensorData3D gyro\n"
"OrientationSensorData orientation\n"
"\n"
"================================================================================\n"
"MSG: gazebo_sensor_collection/SensorData3D\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"DataXYZ covariance\n"
"DataXYZ bias\n"
"DataXYZ offset\n"
"\n"
"================================================================================\n"
"MSG: gazebo_sensor_collection/DataXYZ\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: gazebo_sensor_collection/OrientationSensorData\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"EulerData covariance\n"
"QuaternionData bias\n"
"\n"
"================================================================================\n"
"MSG: gazebo_sensor_collection/EulerData\n"
"float64 roll\n"
"float64 pitch\n"
"float64 yaw\n"
"\n"
"================================================================================\n"
"MSG: gazebo_sensor_collection/QuaternionData\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::gazebo_sensor_collection::ImuData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gazebo_sensor_collection::ImuData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.accel);
      stream.next(m.gyro);
      stream.next(m.orientation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImuData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gazebo_sensor_collection::ImuData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gazebo_sensor_collection::ImuData_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "accel: ";
    s << std::endl;
    Printer< ::gazebo_sensor_collection::SensorData3D_<ContainerAllocator> >::stream(s, indent + "  ", v.accel);
    s << indent << "gyro: ";
    s << std::endl;
    Printer< ::gazebo_sensor_collection::SensorData3D_<ContainerAllocator> >::stream(s, indent + "  ", v.gyro);
    s << indent << "orientation: ";
    s << std::endl;
    Printer< ::gazebo_sensor_collection::OrientationSensorData_<ContainerAllocator> >::stream(s, indent + "  ", v.orientation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAZEBO_SENSOR_COLLECTION_MESSAGE_IMUDATA_H
