# MoveIt-specific simulation settings
moveit_sim_hw_interface:
    joint_model_group: body
    joint_model_group_pose: initial_pose
# Settings for ros_control control loop
generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
    joints:
        - pan_joint
        - tilt_joint
    sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
gazebo_ros_control:
    type: effort_controllers/JointTrajectoryController
    joints:
        - pan_joint
        - tilt_joint
    gains:
        pan_joint: { p: 12000, d: 50, i: 0.0, i_clamp: 10000 }
        tilt_joint: { p: 30000, d: 100, i: 0.02, i_clamp: 10000 }
    constraints:
        goal_time: 2.0
    state_publish_rate: 25

controller_list:
    - name: gazebo_ros_control
      action_ns: "follow_joint_trajectory"
      type: FollowJointTrajectory
      default: true
      joints:
        - pan_joint
        - tilt_joint
